"""confirmed->status

Revision ID: 717f85a34ee5
Revises: 84b254155ff2
Create Date: 2021-06-17 22:28:37.505069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717f85a34ee5'
down_revision = '84b254155ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))
        batch_op.alter_column('time_created',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('time_created',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
