"""transaction confirmed

Revision ID: e629e9a98bbe
Revises: 3e3e4177111a
Create Date: 2021-06-17 20:04:43.769208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e629e9a98bbe'
down_revision = 'a604970f46e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.alter_column('fullname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('time_created', server_default=sa.func.current_timestamp())
        batch_op.add_column(sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('confirmed')
        batch_op.drop_column('time_created')
        batch_op.drop_column('time_updated')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('fullname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
